# Generated by Django 4.0.6 on 2022-07-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
